# I am a comment, and I want to say that the variable CC will be
# the compiler to use.
CC=g++
# Hey!, I am comment number 2. I want to say that CFLAGS will be the
# options I'll pass to the compiler.
OFLAGS=-c -g -ggdb -Wall -std=c++0x
CFLAGS = -g -ggdb -Wall -std=c++0x

AdyTest: AdyMatrix.cpp AdyMatrix.h AdyTest.cpp
	$(CC) $(CFLAGS) AdyMatrix.cpp AdyMatrix.h AdyTest.cpp -o AdyMatrixTest
